#install mariadb app in db group
- name: install mariadb app in db servers
  hosts: db
  tasks:
    - name: install mariadb
      dnf:
        name: mariadb-server
        state: latest
    - name: enable/start the service
      tags:
        - configure
        - db
      ansible.builtin.service: 
        name: mariadb.service
        state: started
        enabled: true
    - name: open firewall port 3306
      ansible.posix.firewalld:
        port: 3306/tcp
        state: enabled
        immediate: yes
        permanent: 1 